name: Python CI

on:
  push:
    branches: [main]
  issue_comment:
    types: [created]

jobs:
  check_comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' # Only runs if the comment is on a PR
    outputs:
      should_run: ${{ steps.comment_check.outputs.should_run }}
    steps:
      - name: Check for 'run tests' comment
        id: comment_check
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const isRunTestsComment = '${{ github.event.comment.body }}'.trim() === 'run tests';
            core.setOutput('should_run', isRunTestsComment ? 'true' : 'false');

  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
        toxenv: [quality, django32]

    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Install Dependencies
      run: pip install -r requirements/ci.txt

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
